pub const Region = struct {
    name: []const u8,
    url: []const u8,
};

pub const REGIONS_LIST = [_]Region{
    .{ .name = "us-east-1 (Virginia)", .url = "https://dynamodb.us-east-1.amazonaws.com/ping" },
    .{ .name = "us-east-2 (Ohio)", .url = "https://dynamodb.us-east-2.amazonaws.com/ping" },
    .{ .name = "us-west-1 (California)", .url = "https://dynamodb.us-west-1.amazonaws.com/ping" },
    .{ .name = "us-west-2 (Oregon)", .url = "https://dynamodb.us-west-2.amazonaws.com/ping" },
    .{ .name = "ca-central-1 (Canada Central)", .url = "https://dynamodb.ca-central-1.amazonaws.com/ping" },
    .{ .name = "ca-west-1 (Canada West)", .url = "https://dynamodb.ca-west-1.amazonaws.com/ping" },
    .{ .name = "eu-west-1 (Ireland)", .url = "https://dynamodb.eu-west-1.amazonaws.com/ping" },
    .{ .name = "eu-west-2 (London)", .url = "https://dynamodb.eu-west-2.amazonaws.com/ping" },
    .{ .name = "eu-west-3 (Paris)", .url = "https://dynamodb.eu-west-3.amazonaws.com/ping" },
    .{ .name = "eu-central-1 (Frankfurt)", .url = "https://dynamodb.eu-central-1.amazonaws.com/ping" },
    .{ .name = "eu-central-2 (Zurich)", .url = "https://dynamodb.eu-central-2.amazonaws.com/ping" },
    .{ .name = "eu-south-1 (Milan)", .url = "https://dynamodb.eu-south-1.amazonaws.com/ping" },
    .{ .name = "eu-south-2 (Spain)", .url = "https://dynamodb.eu-south-2.amazonaws.com/ping" },
    .{ .name = "eu-north-1 (Stockholm)", .url = "https://dynamodb.eu-north-1.amazonaws.com/ping" },
    .{ .name = "il-central-1 (Israel)", .url = "https://dynamodb.il-central-1.amazonaws.com/ping" },
    .{ .name = "me-south-1 (Bahrain)", .url = "https://dynamodb.me-south-1.amazonaws.com/ping" },
    .{ .name = "me-central-1 (UAE)", .url = "https://streams.dynamodb.me-central-1.amazonaws.com/ping" },
    .{ .name = "af-south-1 (Cape Town)", .url = "https://dynamodb.af-south-1.amazonaws.com/ping" },
    .{ .name = "ap-east-1 (Hong Kong)", .url = "https://dynamodb.ap-east-1.amazonaws.com/ping" },
    .{ .name = "ap-southeast-3 (Jakarta)", .url = "https://dynamodb.ap-southeast-3.amazonaws.com/ping" },
    .{ .name = "ap-south-1 (Mumbai)", .url = "https://dynamodb.ap-south-1.amazonaws.com/ping" },
    .{ .name = "ap-south-2 (Hyderabad)", .url = "https://dynamodb.ap-south-2.amazonaws.com/ping" },
    .{ .name = "ap-northeast-3 (Osaka)", .url = "https://dynamodb.ap-northeast-3.amazonaws.com/ping" },
    .{ .name = "ap-northeast-2 (Seoul)", .url = "https://dynamodb.ap-northeast-2.amazonaws.com/ping" },
    .{ .name = "ap-southeast-1 (Singapore)", .url = "https://dynamodb.ap-southeast-1.amazonaws.com/ping" },
    .{ .name = "ap-southeast-2 (Sydney)", .url = "https://dynamodb.ap-southeast-2.amazonaws.com/ping" },
    .{ .name = "ap-southeast-4 (Melbourne)", .url = "https://dynamodb.ap-southeast-4.amazonaws.com/ping" },
    .{ .name = "ap-northeast-1 (Tokyo)", .url = "https://dynamodb.ap-northeast-1.amazonaws.com/ping" },
    .{ .name = "sa-east-1 (São Paulo)", .url = "https://dynamodb.sa-east-1.amazonaws.com/ping" },
    .{ .name = "cn-north-1 (Beijing)", .url = "https://dynamodb.cn-north-1.amazonaws.com.cn/ping" },
    .{ .name = "cn-northwest-1 (Ningxia)", .url = "https://dynamodb.cn-northwest-1.amazonaws.com.cn/ping" },
    .{ .name = "us-gov-east-1", .url = "https://dynamodb.us-gov-east-1.amazonaws.com/ping" },
    .{ .name = "us-gov-west-1", .url = "https://dynamodb.us-gov-west-1.amazonaws.com/ping" },
};

pub const region_count = REGIONS_LIST.len;
